repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .venv/Scripts/python.exe -m pylint
        language: system
        types: [python]
        args: ["--rcfile=pyproject.toml"]